export const hobbyOptions = [
  { label: 'Reading' },
  { label: 'Traveling' },
  { label: 'Music' },
  { label: 'Sports' },
  { label: 'Art & Craft' },
  { label: 'Cooking' },
  { label: 'Meditation' },
  { label: 'Gardening' },
  { label: 'Photography' },
  { label: 'Contributing to Social Activities' },
  { label: 'Intersted / Participating in Aradhana' },
  { label: 'Intersted / Participating in Patha' },
  { label: 'Intersted / Participating in Pravachana' },
  { label: 'Intersted / Participating in Bhajane' },
  { label: 'Intersted / Practicing Puja' },
  { label: 'Intersted / Practicing Sandhyavandane' },
  { label: 'Intersted / Practicing Tulasi Puje' },
  { label: 'Menstruration Practices' },
  { label: 'Observing Chaturmasya' }
];
